# Generated by Django 3.0.4 on 2020-05-11 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym-api', '0002_auto_20200511_0426'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='image',
            field=models.ImageField(null=True, upload_to='exercises/<function Workout.author_name at 0x10e3b0a60>'),
        ),
    ]
