# Generated by Django 3.0.4 on 2020-05-11 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym-api', '0003_exercise_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='exercises/<function Workout.author_name at 0x1036bfa60>'),
        ),
    ]
